{
 "title": "Circular Fast + BAM",
 "tags": [
  "circular",
  "bam"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Circular Fast exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput (recv / enqueue / sent)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "count / interval" }
   ],
   "targets": [
    {
     "query": "SELECT mean(\"received_transactions\") AS received, mean(\"enqueued_transactions\") AS enqueued, mean(\"sent_ok\") AS sent_ok, mean(\"sent_err\") AS sent_err FROM \"testnet\".\"autogen\".\"circular_transaction_exporter\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Drops (queue / in-flight / timeout)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "drops" }
   ],
   "targets": [
    {
     "query": "SELECT mean(\"dropped_batches\") AS dropped_batches, mean(\"dropped_transactions\") AS dropped_tx, mean(\"dropped_no_permit\") AS no_permit, mean(\"dropped_timeout\") AS timeout FROM \"testnet\".\"autogen\".\"circular_transaction_exporter\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Queue depth / capacity / in-flight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "query": "SELECT mean(\"queue_depth\") AS queue_depth, mean(\"queue_capacity\") AS queue_capacity, mean(\"in_flight\") AS in_flight FROM \"testnet\".\"autogen\".\"circular_transaction_exporter\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Latency & bytes (hook_us / send_us)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "us / bytes" }
   ],
   "targets": [
    {
     "query": "SELECT mean(\"hook_us\") AS hook_us, mean(\"send_us\") AS send_us, mean(\"copy_bytes\") AS copy_bytes, mean(\"sent_bytes\") AS sent_bytes FROM \"testnet\".\"autogen\".\"circular_transaction_exporter\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  { "title": "BAM baseline (receive path)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "BAM sigverify",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "us / packets" }
   ],
   "targets": [
    {
     "query": "SELECT mean(\"total_verify_time_us\") AS verify_us, mean(\"total_packets_verified\") AS packets, mean(\"verify_batches_pp_us_p50\") AS p50, mean(\"verify_batches_pp_us_p90\") AS p90 FROM \"testnet\".\"autogen\".\"bam-receive-and-buffer_sigverify-stats\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "BAM receive-and-buffer parse",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "µs", "label": "us" }
   ],
   "targets": [
    {
     "query": "SELECT mean(\"total_us\") AS total_us, mean(\"sanitization_us\") AS sanitization_us, mean(\"resolution_us\") AS resolution_us FROM \"testnet\".\"autogen\".\"bam-receive-and-buffer\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "BAM connection (bundle_received should rise when leader)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "query": "SELECT mean(\"bundle_received\") AS bundle_received, mean(\"heartbeat_received\") AS heartbeat_received, mean(\"leaderstate_sent\") AS leaderstate_sent, mean(\"bundleresult_sent\") AS bundleresult_sent FROM \"testnet\".\"autogen\".\"bam_connection-metrics\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  }
 ]
}